name: veterinary_clinic_mobile
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  device_calendar: ^4.2.0
  timezone: ^0.8.0
  flutter_local_notifications: ^9.4.0
  dart_amqp: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  rename: ^2.0.1

flutter:

  uses-material-design: true